SELECT * FROM tbCliente;

SELECT * FROM tbCliente WHERE IDADE = 22;



SELECT * FROM tbCliente WHERE IDADE > 22;

SELECT * FROM tbCliente WHERE IDADE < 22;

SELECT * FROM tbCliente WHERE IDADE <= 22;

SELECT * FROM tbCliente WHERE IDADE <> 22;

SELECT * FROM tbCliente WHERE NOME => 'Fernando Cavalcante';

SELECT * FROM tbCliente WHERE NOME <> 'Fernando Cavalcante';

SELECT * FROM tbProduto;

SELECT * FROM tbProduto WHERE PRECO_LISTA > 16.008;

SELECT * FROM tbProduto WHERE PRECO_LISTA < 16.008;

SELECT * FROM tbProduto WHERE PRECO_LISTA <> 16.008;

SELECT * FROM tbProduto WHERE PRECO_LISTA BETWEEN 16.007 AND 16.009;