SELECT * FROM tbProduto;

SELECT * FROM tbProduto WHERE PRECO_LISTA BETWEEN 16.007 AND 16.009;
SELECT * FROM tbProduto WHERE PRECO_LISTA >= 16.007;
SELECT * FROM tbProduto WHERE PRECO_LISTA <= 16.009;

SELECT * FROM tbProduto WHERE PRECO_LISTA >= 16.007 AND PRECO_LISTA <= 16.009;

SELECT * FROM tbCliente;

SELECT * FROM tbCliente WHERE IDADE >= 18 AND IDADE <= 22;

SELECT * FROM tbCliente WHERE IDADE >= 18 AND IDADE <= 22 AND SEXO = 'M';

SELECT * FROM tbCliente WHERE CIDADE = 'Rio de Janeiro' OR BAIRRO = 'Jardins';

SELECT * FROM tbCliente WHERE IDADE >= 18 AND IDADE <= 22 AND SEXO = 'M';

SELECT * FROM tbCliente WHERE (IDADE >= 18 AND IDADE <= 22 AND SEXO = 'M') OR
	(cidade = 'Rio de Janeiro' OR BAIRRO = 'Jardins');