SELECT YEAR(DATA_VENDA), FLOOR(SUM(INF.QUANTIDADE * INF.PRECO * NF.IMPOSTO))
FROM notas_fiscais NF
INNER JOIN itens_notas_fiscais INF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY YEAR(DATA_VENDA);