SELECT ADDDATE('2017-06-15', INTERVAL 10 DAY);

SELECT ADDTIME('2017-06-15 09:34:21', '2');

SELECT CURDATE();

SELECT CURRENT_TIME();

SELECT CURRENT_TIMESTAMP();

SELECT DATEDIFF("2017-06-25", "2017-06-15");

SELECT DATE_ADD('2017-06-15', INTERVAL 10 DAY);

SELECT DAYNAME('2017-06-15');

SELECT YEAR(CURRENT_TIMESTAMP());

SELECT DAY(CURRENT_TIMESTAMP());

SELECT MONTH(CURRENT_TIMESTAMP());

SELECT MONTHNAME(CURRENT_TIMESTAMP());

SELECT DATEDIFF(CURRENT_TIMESTAMP(), '2019-01-01') AS RESULTADO;

SELECT DATEDIFF(CURRENT_TIMESTAMP(), '1965-09-04') AS RESULTADO;

SELECT CURRENT_TIMESTAMP() AS DIA_HOJE,
DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 5 DAY) AS RESULTADO;

SELECT DISTINCT DATA_VENDA,
DAYNAME(DATA_VENDA) AS DIA, MONTHNAME(DATA_VENDA) AS MES,
YEAR(DATA_VENDA) AS ANO FROM notas_fiscais;